# 数据的重要性

In [2]:
import pandas as pd
from sklearn.datasets import load_iris

data = load_iris()
X = pd.DataFrame(data.data, columns=data.feature_names)
y = pd.DataFrame(data.target, columns=["Species"])
df = pd.concat([ X,y], axis=1)
df.head()

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                5.1               3.5                1.4               0.2   
1                4.9               3.0                1.4               0.2   
2                4.7               3.2                1.3               0.2   
3                4.6               3.1                1.5               0.2   
4                5.0               3.6                1.4               0.2   

   Species  
0        0  
1        0  
2        0  
3        0  
4        0

# 有监督学习（分类）的例子

In [3]:
from sklearn.datasets import load_breast_cancer
from sklearn.model_selection import train_test_split
data = load_breast_cancer()

cancers = load_breast_cancer()
X = cancers.data       #获取特征值
Y = cancers.target     #获取标签
print(X.shape)         #查看特征形状
print(Y.shape)         #查看标签形状

print(X)
print(Y)


print(data.DESCR)  #查看数据集描述

print('特征名称')
print(data.feature_names)  # 特征名
print('分类名称')
print(data.target_names)  # 标签类别名

# 注意返回值： 训练集train，x_train，y_train，测试集test，x_test，y_test
# x_train为训练集的特征值，y_train为训练集的目标值，x_test为测试集的特征值，y_test为测试集的目标值
# 注意，接收参数的顺序固定
# 训练集占80%，测试集占20%
x_train, x_test, y_train, y_test = train_test_split(X, Y, test_size=0.2)
print('训练集的特征值和目标值：', x_train, y_train)
print('测试集的特征值和目标值：', x_test, y_test)

#dict_keys(['data', 'target', 'target_names', 'DESCR', 'feature_names', 'filename'])
print(cancers.keys())




(569, 30)
(569,)
[[1.799e+01 1.038e+01 1.228e+02 ... 2.654e-01 4.601e-01 1.189e-01]
 [2.057e+01 1.777e+01 1.329e+02 ... 1.860e-01 2.750e-01 8.902e-02]
 [1.969e+01 2.125e+01 1.300e+02 ... 2.430e-01 3.613e-01 8.758e-02]
 ...
 [1.660e+01 2.808e+01 1.083e+02 ... 1.418e-01 2.218e-01 7.820e-02]
 [2.060e+01 2.933e+01 1.401e+02 ... 2.650e-01 4.087e-01 1.240e-01]
 [7.760e+00 2.454e+01 4.792e+01 ... 0.000e+00 2.871e-01 7.039e-02]]
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 1 0 0 0 0 0 0 0 0 1 0 1 1 1 1 1 0 0 1 0 0 1 1 1 1 0 1 0 0 1 1 1 1 0 1 0 0
 1 0 1 0 0 1 1 1 0 0 1 0 0 0 1 1 1 0 1 1 0 0 1 1 1 0 0 1 1 1 1 0 1 1 0 1 1
 1 1 1 1 1 1 0 0 0 1 0 0 1 1 1 0 0 1 0 1 0 0 1 0 0 1 1 0 1 1 0 1 1 1 1 0 1
 1 1 1 1 1 1 1 1 0 1 1 1 1 0 0 1 0 1 1 0 0 1 1 0 0 1 1 1 1 0 1 1 0 0 0 1 0
 1 0 1 1 1 0 1 1 0 0 1 0 0 0 0 1 0 0 0 1 0 1 0 1 1 0 1 0 0 0 0 1 1 0 0 1 1
 1 0 1 1 1 1 1 0 0 1 1 0 1 1 0 0 1 0 1 1 1 1 0 1 1 1 1 1 0 1 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 1 1 1 1 1 1 0 1 0 1 1 0 1 1 0 1 0 0

In [4]:
X = data.data
y = data.target
X_pd = pd.DataFrame(data.data, columns=data.feature_names)
X_pd.head()

print("before slice", X.shape)
X = X[:, :10]
print("after slice", X.shape)



before slice (569, 30)
after slice (569, 10)


## 实现方法

In [5]:
from sklearn.linear_model import LogisticRegression
model = LogisticRegression()

In [6]:
model.fit(X, y)

LogisticRegression()

In [7]:
y_pred = model.predict(X)

In [8]:
from sklearn.metrics import accuracy_score
accuracy_score(y, y_pred)

0.9121265377855887

# 无监督学习（聚类）的例子

In [9]:
from sklearn.datasets import load_wine
data = load_wine()

In [10]:
X = data.data[:, [0, 9]]


## 实现方法

In [11]:
from sklearn.cluster import KMeans
n_clusters = 3
model = KMeans(n_clusters=n_clusters)

In [12]:
pred = model.fit_predict(X)

## 查看结果

In [13]:
%matplotlib inline
import matplotlib.pyplot as plt
fig, ax = plt.subplots()
ax.scatter(X[pred==0, 0], X[pred==0, 1], color='red', marker='s', label='Label1')
ax.scatter(X[pred==1, 0], X[pred==1, 1], color='blue', marker='s', label='Label2')
ax.scatter(X[pred==2, 0], X[pred==2, 1], color='green', marker='s', label='Label3')
ax.scatter(model.cluster_centers_[:, 0], model.cluster_centers_[:, 1], s=200, color='yellow', marker="*", label="center")
ax.legend()
plt.show()

ModuleNotFoundError: No module named 'matplotlib'

# 图形的种类和画法：使用Matplotlib显示图形的方法

In [ ]:
%matplotlib inline

In [ ]:
import numpy as np
import matplotlib.pyplot as plt

In [ ]:
x1 = np.linspace(-5, 5, 101)
y1 = np.sin(x1)
print(x1)
print(y1)

In [ ]:
plt.plot(x1, y1)

In [ ]:
fig, ax = plt.subplots()
ax.set_title("Sin")
ax.set_xlabel("rad")
ax.plot(x1, y1)
handles, labels = ax.get_legend_handles_labels()
ax.legend(handles, labels)
plt.show()

## 绘制各种图形

In [ ]:
x2 = np.arange(100)
y2 = x2 * np.random.rand(100)

In [ ]:
plt.scatter(x2, y2)

In [ ]:
plt.hist(y2, bins=5)

In [ ]:
plt.bar(x2, y2)

In [ ]:
plt.plot(x2, y2)

In [ ]:
plt.boxplot(y2)

## 红酒数据集

In [ ]:
from sklearn.datasets import load_wine
data = load_wine()

In [ ]:
x3 = data.data[:, [0]]
y3 = data.data[:, [9]]

In [ ]:
plt.scatter(x3, y3)

In [ ]:
plt.hist(y3, bins=5)

# 使用pandas理解和处理数据

In [ ]:
import pandas as pd

In [ ]:
from sklearn.datasets import load_wine
data = load_wine()
df_X = pd.DataFrame(data.data, columns=data.feature_names)

In [ ]:
df_X.head()

In [ ]:
df_y = pd.DataFrame(data.target, columns=["kind(target)"])

In [ ]:
df_y.head()

In [ ]:
df = pd.concat([df_X, df_y], axis=1)

In [ ]:
df.head()

In [ ]:
plt.hist(df.loc[:, "alcohol"])

In [ ]:
plt.boxplot(df.loc[:, "alcohol"])

In [ ]:
df.corr()

In [ ]:
df.describe()

In [ ]:
from pandas.plotting import scatter_matrix
_ = scatter_matrix(df, figsize=(15, 15))

In [ ]:
_ = scatter_matrix(df.iloc[:, [0, 9, -1]])